export enum CMD {
    POSTS_SUB = 'POSTS_SUB',
    POST_DETAILS_SUB = 'POST_DETAILS_SUB',
    GLOBAL_STATE_SUB = 'GLOBAL_STATE_SUB',
    SPEED_SUB = 'SPEED_SUB',
    USER_SUB = 'USER_SUB',
    THREAD_PARSING_SUB = 'THREAD_PARSING_SUB',
    GRAB_QUEUE_SUB = 'GRAB_QUEUE_SUB',
    POSTS_UNSUB = 'POSTS_UNSUB',
    POST_DETAILS_UNSUB = 'POST_DETAILS_UNSUB',
    GLOBAL_STATE_UNSUB = 'GLOBAL_STATE_UNSUB',
    SPEED_UNSUB = 'SPEED_UNSUB',
    USER_UNSUB = 'USER_UNSUB',
    THREAD_PARSING_UNSUB = 'THREAD_PARSING_UNSUB',
    GRAB_QUEUE_UNSUB = 'GRAB_QUEUE_UNSUB'
}
