export enum CMD {
    POSTS_SUB = 'POSTS_SUB',
    POST_DETAILS_SUB = 'POST_DETAILS_SUB',
    GLOBAL_STATE_SUB = 'GLOBAL_STATE_SUB',
    SPEED_SUB = 'SPEED_SUB',
    POSTS_UNSUB = 'POSTS_UNSUB',
    POST_DETAILS_UNSUB = 'POST_DETAILS_UNSUB',
    GLOBAL_STATE_UNSUB = 'GLOBAL_STATE_UNSUB',
    SPEED_UNSUB = 'SPEED_UNSUB'
}
